# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

AWSTemplateFormatVersion: 2010-09-09
Description: >-
  sam-dynamodb-s3-export

Transform:
  - AWS::Serverless-2016-10-31

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: "Delete"
    DeletionPolicy: "Delete"
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  # Func1SeedDynamoDb:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     Description: func1 - init ddb
  #     Runtime: nodejs18.x
  #     Architectures:
  #       - x86_64
  #     CodeUri: lambdas/func1-seed-ddb
  #     Handler: app.handler
  #     MemorySize: 128
  #     Timeout: 120
  #     Policies:
  #     - AmazonDynamoDBFullAccess

  # InitializeDynamoDB:
  #   Type: Custom::InitFunction
  #   Properties:
  #     ServiceToken:
  #       Fn::GetAtt: [Func1SeedDynamoDb, "Arn"]
  #     DynamoTableName:
  #       Ref: DynamoDBTable

  S3Bucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Delete

  ScheduledTableExporter:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs18.x
      CodeUri: lambdas/func2-scheduled-exporter
      Handler: app.handler
      MemorySize: 128
      Timeout: 120
      Environment:
        Variables:
          S3_BUCKET: !Ref S3Bucket
          DYNAMODB_TABLE: !Ref DynamoDBTable
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: cron(*/10 * * * ? *)
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
