AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Stack used to demonstrate how to export dynamodb table data on a schedule 

Transform:
  - AWS::Serverless-2016-10-31

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: "Delete"
    DeletionPolicy: "Delete"
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  S3Bucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Delete

  Func1ScheduledDataGenerator:
    Type: AWS::Serverless::Function
    Properties:
      Description: "Inserts mock data to dynamodb table at scheduled intervals"
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      CodeUri: lambdas/func1-data-generator
      Handler: app.handler
      MemorySize: 128
      Timeout: 120
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref DynamoDBTable
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: cron(*/5 * * * ? *)
      Policies:
        - AmazonDynamoDBFullAccess

  Func2ScheduledTableExporter:
    Type: AWS::Serverless::Function
    Properties:
      Description: "Exports data from dyanmodb table to s3 bucket at scheduled intervals"
      Runtime: nodejs18.x
      CodeUri: lambdas/func2-data-exporter
      Handler: app.handler
      MemorySize: 128
      Timeout: 120
      Environment:
        Variables:
          S3_BUCKET: !Ref S3Bucket
          DYNAMODB_TABLE: !Ref DynamoDBTable
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: cron(*/10 * * * ? *)
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
