name: Simple CI/CD pipeline to build and deploy a AWS SAM app

on:
  push:
    branches:
      - "master"

env:
  AWS_REGION: ap-south-1
  PIPELINE_IAM_ROLE: ${{ secrets.PIPELINE_IAM_ROLE }}

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Build
        run: sam build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ env.PIPELINE_IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
          mask-aws-account-id: true

      - name: Deploy
        run: |
          sam deploy \
            --parameter-overrides ParameterKey=GitHubOrg,ParameterValue=$GITHUB_REPOSITORY_OWNER ParameterKey=GitHubRepoName,ParameterValue=${GITHUB_REPOSITORY#*/} \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset
